import { join } from "path";

export const webRoutes = {
  home: '/',
  login: '/login',
  logout: '/logout',
  register: '/register',
  checkout: '/checkout',
  dashboard: '/dashboard',
  dashboard_menus: '/dashboard/menus',
  dashboard_meals: '/dashboard/meals',
  dashboard_meals_add: '/dashboard/meals/add',
  dashboard_meals_edit: '/dashboard/meals/edit/:id',
  dashboard_meals_view: '/dashboard/meals/view/:id',
  dashboard_weekly_menus: '/dashboard/weekly-menus',
  dashboard_weekly_menus_add: '/dashboard/weekly-menus/add',
  dashboard_weekly_menus_edit: '/dashboard/weekly-menus/edit/:id',
  dashboard_weekly_menus_view: '/dashboard/weekly-menus/view/:id',
  dashboard_users: '/dashboard/users',
  dashboard_users_add: '/dashboard/users/add',
  dashboard_users_edit: '/dashboard/users/edit/:id',
  dashboard_users_view: '/dashboard/users/view/:id',
  dashboard_orders: '/dashboard/orders',
  dashboard_orders_add: '/dashboard/orders/add',
  dashboard_orders_edit: '/dashboard/orders/edit/:id',
  dashboard_orders_view: '/dashboard/orders/view/:id',
  dashboard_plans: '/dashboard/plans',
  dashboard_plans_add: '/dashboard/plans/add',
  dashboard_plans_edit: '/dashboard/plans/edit/:id',
  dashboard_plans_view: '/dashboard/plans/view/:id',
  dashboard_membership_plans: '/dashboard/membership-plans',
  dashboard_membership_plans_add: '/dashboard/membership-plans/add',
  dashboard_membership_plans_edit: '/dashboard/membership-plans/edit/:id',
  dashboard_membership_plans_view: '/dashboard/membership-plans/view/:id',
  dashboard_memberships: '/dashboard/memberships',
  dashboard_memberships_view: '/dashboard/memberships/view/:id',
  dashboard_categories: '/dashboard/categories',
  dashboard_categories_add: '/dashboard/categories/add',
  dashboard_categories_edit: '/dashboard/categories/edit/:id',
  dashboard_categories_view: '/dashboard/categories/view/:id',
  dashboard_meal_preparation: '/dashboard/meal-preparation',
  dashboard_rewards: '/dashboard/rewards',

  menu: '/menu',
  meal_single: '/meal/:id',
  join_now: '/join-now',
  membership_plans: '/membership-plans',
  membership_checkout: '/membership-checkout/:planId',
  thank_you: '/thank-you/:orderId',
  single_product: '/product/:id',
  privacy_policy: '/privacy-policy',
  terms_service: '/terms-of-service',
  cookie_settings: '/cookie-settings',


};
